# Generated by Django 3.0.5 on 2020-05-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='rolePro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tablecom.CategoriePro'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='statusRL',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
