# Generated by Django 3.0.5 on 2020-05-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0002_auto_20200502_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id_ChildSNotebook',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='mail',
        ),
        migrations.AddField(
            model_name='childsnotebook',
            name='articles_id',
            field=models.TextField(default='', max_length=2500, verbose_name='Id des articles rattachés'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='rolePro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tablecom.CategoriePro', verbose_name='Catégorie si professionnel'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='statusRL',
            field=models.CharField(default='NA', max_length=20, verbose_name='Catégorie si reponsable légal'),
        ),
    ]
