# Generated by Django 3.0.5 on 2020-05-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0003_auto_20200503_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Votre message')),
                ('username', models.CharField(max_length=255, verbose_name='UserName')),
                ('first_name', models.CharField(max_length=255, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('num_ident', models.CharField(max_length=255, verbose_name="Numéro d'identité")),
                ('phone', models.CharField(max_length=60, null=True)),
                ('RLorPro', models.CharField(choices=[('0', 'Pro'), ('1', 'RL')], max_length=11)),
                ('statusRL', models.CharField(default=0, max_length=25, verbose_name='statusRL')),
                ('rolePro', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tablecom.CategoriePro', verbose_name='Catégorie si professionnel')),
            ],
        ),
    ]
