# Generated by Django 3.0.5 on 2020-05-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0004_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='statusRL',
            field=models.CharField(default='', max_length=25, verbose_name='statusRL'),
        ),
    ]
