# Generated by Django 3.0.5 on 2020-05-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0005_auto_20200509_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='RLorPro',
            field=models.CharField(choices=[('0', 'Pro'), ('1', 'RL')], default='0', max_length=11),
        ),
    ]
