# Generated by Django 3.0.5 on 2020-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0009_auto_20200509_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=models.TextField(verbose_name='Votre message*'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email*'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre'),
        ),
    ]
