# Generated by Django 3.0.5 on 2020-05-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0007_auto_20200509_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='rolePro',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablecom.CategoriePro', verbose_name='Catégorie si professionnel'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='statusRL',
            field=models.CharField(default=' ', max_length=25, null=True, verbose_name='Statut si résponsable légal (Mère, Père, Tuteur, ...)'),
        ),
    ]
