# Generated by Django 3.0.5 on 2020-05-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0008_auto_20200509_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='num_ident',
            field=models.CharField(blank=True, max_length=255, verbose_name="Numéro d'identité"),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='rolePro',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='tablecom.CategoriePro', verbose_name='Catégorie si professionnel'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='statusRL',
            field=models.CharField(blank=True, default=' ', max_length=25, verbose_name='Statut si résponsable légal (Mère, Père, Tuteur, ...)'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name="Nom d'utilisateur"),
        ),
    ]
