# Generated by Django 3.1.3 on 2020-11-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0011_auto_20200509_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='num_ident',
        ),
    ]
