# Generated by Django 3.1.3 on 2020-11-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0012_remove_contactus_num_ident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='valid_art',
            field=models.BooleanField(default=True),
        ),
    ]
