# Generated by Django 3.1.3 on 2020-11-17 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tablecom', '0014_remove_article_list_to_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='DeletedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de supression'),
            preserve_default=False,
        ),
    ]
