# Generated by Django 3.1.3 on 2020-11-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepersoat',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagepersoat',
            name='validated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messagepersoat',
            name='contenu',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='messagepersoat',
            name='titre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
