# Generated by Django 3.0.5 on 2020-05-10 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DJInterCom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondanceTableMessagesByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=6)),
                ('messagesAccess', models.TextField(blank=True, default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='messageperso',
            name='accessUserID',
            field=models.CharField(default='0', max_length=80),
        ),
        migrations.AlterField(
            model_name='messageperso',
            name='auteurID',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='messageperso',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi'"),
        ),
    ]
