# Generated by Django 3.0.5 on 2020-05-10 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePerso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteurID', models.CharField(max_length=5)),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('accessUserID', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Message Privé',
                'ordering': ['date'],
            },
        ),
    ]
