# Generated by Django 3.1.3 on 2020-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DJInterCom', '0002_auto_20200510_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageperso',
            name='AttachedChildNotebookID',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
